### ISSUE TITLE
Some missing cases

### ISSUE THREAD

**Issue by manumeter** [cyril/opushon#1]
I like this idea of a self describing API very much and I'm consider changing my APIs using this technique. However, I'm missing the following details:

- What is the exact meaning of `restricted_values`? Is it an exclusive list of possible values? If so, wouldn't it make more sense to define an own `type` for it (I think they are redundant or even inconsistent otherwise).
- How do you describe an option of the type `hash` (in particular, its child options)?
- How do you handle mixed types? (Yes, it might be ugly, but in practice, very useful sometimes, e.g. depending on values in the `query_string`.)
- In your examples, your request is like `OPTIONS /issues`, what would be the desired way to get the documentation on objects or sub-objects? (e.g. something like `OPTIONS /issues/232/comment/2` which would return the same for any valid issue and comment ID or a more generic request like `OPTIONS /issues/:id/comment/:id`)
- How would you hint about sub-objects available?

**Comment by cyril** [comment]
I'm happy to read your questions! Thanks for your interest.


> What is the exact meaning of `restricted_values`? Is it an exclusive list of possible values? If so, wouldn't it make more sense to define an own `type` for it (I think they are redundant or even inconsistent otherwise).

Yes, it is an exclusive list of possible values. It is like the HTML `<select>` element, which provides a list of values from which the client can choose.

Even if each value have to respect one same common type (the `type` of the attribute), the benefit of being explicit is that the client wouldn't have to guess it through a look at the list of the given values.

But I see your point, it's kinda redundant, and it could become inconsistent if some possible values have a different type.


> How do you describe an option of the type `hash` (in particular, its child options)?

I think about this type of data like any other type of value (not as an embedded resource, to avoid complexity).


> How do you handle mixed types? (Yes, it might be ugly, but in practice, very useful sometimes, e.g. depending on values in the `query_string`.)

Currently, this is not supported, type takes a single value.


> In your examples, your request is like `OPTIONS /issues`, what would be the desired way to get the documentation on objects or sub-objects? (e.g. something like `OPTIONS /issues/232/comment/2` which would return the same for any valid issue and comment ID or a more generic request like `OPTIONS /issues/:id/comment/:id`)

The client would have to perform an `OPTIONS` request to get the documentation on some other objects or sub-objects.


> How would you hint about sub-objects available?

Thanks to [Web Linking](http://www.rfc-editor.org/rfc/rfc5988.txt), the client can discover resources (and, using `OPTIONS`, see their documentation).
